### ISSUE TITLE
Request a specific Custom Model during text-to-image generation

### ISSUE THREAD

**Issue by oksidor** [AdobeDocs/ff-services-docs#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature should be added?

Ability to request a specific Custom Model during text-to-image generation via Firefly API

### What is the expected behavior?

In addition to the existing parameters, the API should accept a `customModel` parameter, which will apply one of the custom models defined by a Firefly Enterprise client

### How will this feature improve the user experience?

It will enable enterprise customers to generate on-brand images

### What would a solution for this issue look like?

Another API parameter, `customModel`

**Comment by sushiriot** [comment]
Contact your Adobe representative; Custom Models are currently on the product roadmap for 2025.
