### ISSUE TITLE
The price to use the firefly api to generate text2image.

### ISSUE THREAD

**Issue by Pjumpod** [AdobeDocs/ff-services-docs#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Missing the document to describe the price when use an api to generate the text2image function.

Is the price totally same price with generate from firefly website? If yes, this is very great!!

**Comment by bishoysefin** [comment]
Hi @Pjumpod 

Contact your Adobe representative if you already have an existing enterprise license. Firefly Services APIs (Firefly, Photoshop & Lightroom) are currently under limited availability to existing enterprise licensees.
